export const SET_WORKOUT = "SET_WORKOUT";
export const INCREMENT_INDEX = "INCREMENT_INDEX";
export const DECREMENT_TIMER = "DECREMENT_TIMER";
export const WORKOUT_COMPLETED = "WORKOUT_COMPLETED";
export const CLEAR_WORKOUT = "CLEAR_WORKOUT";
export const RESET_CURRENT_WORKOUT = "RESET_CURRENT_WORKOUT";
export const BEGIN_WORKOUT = "BEGIN_WORKOUT";
export const PAUSE_WORKOUT = "PAUSE_WORKOUT";
export const CHANGE_REPS = "CHANGE_REPS";
export const SET_REPS = "SET_REPS";
export const INCREMENT_REP_COUNT = "INCREMENT_REP_COUNT";


export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";
export const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";


export const CREATE_NEW_ROUTINE_SUCCESS = "CREATE_NEW_ROUTINE_SUCCESS";
export const FETCH_ROUTINES_SUCCESS = "FETCH_ROUTINES_SUCCESS";
export const DELETE_ROUTINE_SUCCESS = "DELETE_ROUTINE_SUCCESS";
export const UPDATE_ROUTINE_SUCCESS = "UPDATE_ROUTINE_SUCCESS";


export const SET_EDIT_ROUTINE = "SET_EDIT_ROUTINE";
export const SELECT_EXERCISE = "SELECT_EXERCISE";
export const SET_DURATION = "SET_DURATION";
export const REMOVE_EXERCISE = "REMOVE_EXERCISE";
export const DURATION_CHANGE = "DURATION_CHANGE";
export const NAME_CHANGE = "NAME_CHANGE";
