export const SET_WORKOUT = "SET_WORKOUT";
export const INCREMENT_INDEX = "INCREMENT_INDEX";
export const DECREMENT_TIMER = "DECREMENT_TIMER";
export const WORKOUT_COMPLETED = "WORKOUT_COMPLETED";
export const CLEAR_WORKOUT = "CLEAR_WORKOUT";
export const RESET_CURRENT_WORKOUT = "RESET_CURRENT_WORKOUT";
export const BEGIN_WORKOUT = "BEGIN_WORKOUT";
export const PAUSE_WORKOUT = "PAUSE_WORKOUT";
